apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ceappacr.azurecr.io/82212582
  newTag: "202410280648"

configMapGenerator:
- literals:
  - spring.profiles.active=prod
  name: app-config
